### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by israelsantiago** [shankardevy/mango#1]
Hi,

Please, I have completed the installation procedures but the product images were not found:

[Info] GET /product_images/Watermelon.jpeg
[Debug] ** (Phoenix.Router.NoRouteError) no route found for GET /product_images/Watermelon.jpeg (Mango.Web.Router)
    (Mango) lib / mango / web / router.ex: 1: Mango.Web.Router .__ match_route __ / 4
    (Mango) lib / phoenix / router.ex: 303: Mango.Web.Router.call/2
    (Mango) lib / mango / web / endpoint.ex: 1: Mango.Web.Endpoint.plug_builder_call / 2
    (Mango) lib / plug / debugger.ex: 123: Mango.Web.Endpoint. "Call (overridable 3)" / 2
    (Mango) lib / mango / web / endpoint.ex: 1: Mango.Web.Endpoint.call/2
    (Plug) lib / plug / adapters / cowboy / handler.ex: 15: Plug.Adapters.Cowboy.Handler.upgrade / 4
    (Cowboy) /Users/irs/Elixir/phoenix/mango/deps/cowboy/src/cowboy_protocol.erl:442:: cowboy_protocol.execute / 4

Thank you,
Israel Santiago

**Comment by shankardevy** [comment]
@israelsantiago 

Please download the additional files required for the chapters at: https://shankardevy.com/phoenix-book/book_files.zip

I am going to update the README file with this information.

**Comment by israelsantiago** [comment]
I can not find the image files in this file:book_files.zip :-(

**Comment by shankardevy** [comment]
Sorry, please download a fresh copy now. The images are present in `book_files/seed_data/product_images/`
