### ISSUE TITLE
Add to cart replaces existing items

### ISSUE THREAD

**Issue by clindholm** [shankardevy/mango#2]
When following the book, the end result is that when adding items to the cart they replace the existing one. It might be that I missed something but I've re-read those sections many times now. If we had the final code available it would be much easier to double check for errors.

**Comment by shankardevy** [comment]
@clindholm will have the final code early next week. Please bear with me for the delay.

**Comment by shankardevy** [comment]
@clindholm I am modifying the order of Chapter 5 and 6 slightly so I haven't pushed the code for these chapter yet.  Please use the code below for add to cart. This will resolve the issue you have reported. However, if you add the same product twice, this code will not consolidate them into a single line item.

```elixir
  def add_to_cart(%Order{line_items: []} = cart, cart_params) do
    attrs = %{ line_items: [cart_params] }
    update_cart(cart, attrs)
  end

  def add_to_cart(%Order{line_items: existing_line_items} = cart, cart_params) do
    new_item = %{
      product_id: String.to_integer(cart_params["product_id"]),
      quantity: String.to_integer(cart_params["quantity"])
    }
    existing_line_items = existing_line_items |> Enum.map(&Map.from_struct/1)

    attrs = %{ line_items: [ new_item | existing_line_items ] }
    update_cart(cart, attrs)
  end

  def update_cart(cart, attrs) do
    cart
    |> Order.changeset(attrs)
    |> Repo.update
  end
```
