### ISSUE TITLE
Bootstrap layout fault

### ISSUE THREAD

**Issue by kieranwild** [shankardevy/mango#6]
Thanks for the great book. I am having slight problem with bootstrap layout. It looks like this:
![image](https://user-images.githubusercontent.com/55413/33771416-da893816-dc28-11e7-8c5e-3fabf81ead3e.png)

**Comment by shankardevy** [comment]
can you share your repo? It should work without any layout issue with the stylesheets in this repo.

**Comment by shankardevy** [comment]
Closing this as there is no response. Feel free to open again if you have more information.
